### ISSUE TITLE
node_modules/@ngrx/effects/index"' has no exported mng 'runEffects'.

### ISSUE THREAD

**Issue by iwoogy** [ngrx/effects#37] opened 2016-08-17 10:09 UTC
Hello,

My app cannot compile while adding 
`import { runEffects } from '@ngrx/effects';`
to my main.ts file

This error appears :
`Module '"/path/to/project/node_modules/@ngrx/effects/index"' has no exported mng 'runEffects'.`

Context :
[package.json.zip](https://github.com/ngrx/effects/files/422283/package.json.zip)

Thanks for your help.

Bobby

**Comment by stefanos-** [comment] 2016-08-17 10:52
You are using npm 2.0.0-beta.2 version of @ngrx/effects. You should check this: https://github.com/ngrx/effects/blob/v2.0.0-beta.2/README.md. In my opinion is not good practice to import things in main.ts. You should configure your app in app.module.ts

**Comment by iwoogy** [comment] 2016-08-17 11:24
Hello,

Thanks, I was trying to use the content of main.browser.ts to bootstrap my application.
https://github.com/ngrx/example-app/blob/master/src/main.browser.ts

I'm using angular-cli, so I put the content of main.browser.ts into main.ts.

However since the upgrade to RC5, bootstrapping an application is now different using NgModule.

Do you have any timeline for an updating version of https://github.com/ngrx/example-app ?
In order to see what are the best practices to setup a new application with angular-cli and ngrx ?

Best regards

Bobby

**Comment by stefanos-** [comment] 2016-08-17 11:44
I'm not working right now with angular-cli. Your angular-cli project and the example-app have been built differently. Don't compare them. Exampe-app is a good paradigm to implement @ngrx/store/effects... in your project but you should follow the angular-cli way.

**Comment by wiredprogrammer** [comment] 2016-08-25 16:26
What is the suggested method for registering multiple effects at once in the beta?  It used to be you could pass in an array of effects modules.

**Comment by MikeRyan52** [comment] 2016-08-25 16:27
@wiredprogrammer In order to keep the DI statically analyzable for the AOT compiler you have to call `EffectsModule.run()` multiple times for each effect class:

```ts
@NgModule({
  imports: [
    EffectsModule.run(EffectsA),
    EffectsModule.run(EffectsB),
    EffectsModule.run(EffectsC)
  ]
})
export class AppModule { }
```

**Comment by wiredprogrammer** [comment] 2016-08-25 16:38
Would something like this work okay then?  
````javascript
let _effects = [ 
    EffectsA,
    EffectsB,
    EffectsC
];
_effects = _effects.reduce((_newEffects, effectModule) => {
    _newEffects.push(EffectsModule.run(effectModule));
    return _newEffects;
}, []);
export default _effects;
````
 and then this

````javascript
import effects from './effects';
@NgModule({
  imports: [
    effects
  ]
})
export class AppModule { }
````
Any suggested reading to make sure my code is AoT friendly?

**Comment by stefanos-** [comment] 2016-08-25 20:12
There is a good article for AoT from [mgechev](http://blog.mgechev.com/2016/08/14/ahead-of-time-compilation-angular-offline-precompilation/v). There is also a commit in his  seed project where you can see some things in practice. [commit](https://github.com/mgechev/angular2-seed/commit/bf5a3322329ecc603ea97d101da79f789cb3d70b).

**Comment by fxck** [comment] 2016-09-02 07:57
@wiredprogrammer 

```
effects.map(effect => EffectsModule.run(effect))
```

**Comment by MikeRyan52** [comment] 2016-09-27 00:34
Sorry for the confusion! My mistake marking the beta release with the dist tag. Docs are all fixed now.

**Closed by MikeRyan52** 2016-09-27 00:34 UTC

**Comment by maxime1992** [comment] 2016-10-11 07:07
@MikeRyan52 I don't understand your message : https://github.com/ngrx/effects/issues/37#issuecomment-242451986

I'm building my app with AOT and everything works fine except for effect.
For example, I do have this code : 
```typescript
  @Effect({dispatch: true}) usr_connect$: Observable<{ type: string }> = this.actions$
    .ofType(USR_IS_CONNECTING)
    .switchMap(action => this.userService.connectUser(action.payload)
      .map((res: any) => {
        console.log('res ', res);
        this.router.navigate(['/cockpit']);
        return { type: USR_IS_CONNECTED, payload: res };
      })
      .catch((err) => {
        console.log(err);
        if (environment.debug) {
          console.error(err);
        }

        return Observable.of({ type: USR_CONNECTION_FAILED });
      })
    );
```

And nothing happens. I think I need to do what you wrote in your comment but I don't understand.
In the constructor I've made `this.actions$.subscribe(data => console.log('data ', data));` and I do have the log of `USR_IS_CONNECTING`.

My app.module is like that : 
```typescript
@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    // angular
    BrowserModule,
    SharedModule,
    FeatureModule,
    FormsModule,

    // ngrx - store
    StoreModule.provideStore({
      config: ConfigReducer,
      user: UserReducer,
      workspaces: WorkspacesReducer
    }),

    EffectsModule.runAfterBootstrap(UserEffects),

    // translate
    TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: createTranslateLoader,
      deps: [Http]
    }),

    // material design
    MaterialModule.forRoot(),
  ],
  providers: [
    UserEffects,
    {
      provide: UserService,
      useClass: (environment.mock ? UserMockService : UserService)
    }
  ],
  bootstrap: [
    AppComponent
  ]
})
export class AppModule { }
```

**Comment by MikeRyan52** [comment] 2016-10-11 12:26
@maxime1992 Everything in the effects looks fine. If I had to guess without trying to run the AOT compiler on your code, I'd bet it is the conditional class provider for `UserService` in your providers list. Also, you do not need to provide `UserEffects`; it is already provided for you when you pass it to `EffectsModule.run(token)`

**Comment by maxime1992** [comment] 2016-10-11 13:32
@MikeRyan52 ok, I tried but it doesn't work.

`EffectsModule.run(UserEffects),` does not work
`EffectsModule.runAfterBootstrap(UserEffects),` does not work

I also tried with simply the mock service ... but doesn't change anything
```javascript
providers: [
  UserEffects,
  {
    provide: UserService,
    useClass: UserMockService
  }
]
```

No error at compilation, but same problem.
The effect is not run.
<hr>
IF you ever have some time to help me figure out what's not working here :
(otherwise no problem, I can imagine that the problem is related to me and it's probably not a bug from effects so I would totally understand)

1. Source code is available here : https://gitlab.com/victornoel/petals-cockpit

2. To reproduce the current behaviour : 
```
git clone https://gitlab.com/victornoel/petals-cockpit.git
git checkout 6f427fb05b1c0fadfeca1d1ab60eb7a47662a2ed
cd petals-cockpit/frontend
npm i
ng serve --aot
```

Go to
- [http://localhost:4200/cockpit/workspaces](http://localhost:4200/cockpit/workspaces) and try to logout (top left corner)  
and/or  
- [http://localhost:4200/login](http://localhost:4200/login) and try to login (empty form is ok)
