### ISSUE TITLE
DI issue when running effects on Ionic V2 app

### ISSUE THREAD

**Issue by benorama** [ngrx/effects#20] opened 2016-06-27 14:16 UTC
In an Ionic2 app, we are getting DI error during app bootstrap: `No provider for StateUpdates! (Token Application Initializer -> Token @ngrx/effects Bootstrap Effects -> StateUpdates)`.

Same code is working fine on a regular Angular2 app.

Here is a repo to reproduce the issue:
https://github.com/benorama/ngrx-demo-apps

On the working web version, there is an effect on RESET action which just does a console.log and then dispatch the RESET_SUCCESS action.

On the broken mobile version, it generates the DI exception during app bootstrap.
Uncomment the `runEffects` provider in app.ts  and then `ionic serve` to reproduce the issue:
https://github.com/benorama/ngrx-demo-apps/blob/master/mobile/app/app.ts

**Comment by jimitndiaye** [comment] 2016-07-07 13:55
I'm encountering the same issue. The problem seems to be that runEffects uses a map against the provided effect classes so if you don't have any effects registered (you provide an empty array) none of the Bootstrap Effects get registered and you get that error.
The solution for me was to either ensure that the provided effects array is non-empty or to use the mergeEffects function to register effects after application start up.

**Comment by benorama** [comment] 2016-07-08 08:53
@jimitndiaye do you have any example to demonstrate a workaround with `mergeEffects`?

I just tried the `mergeEffects` approach, but still the same issue:
https://github.com/benorama/ngrx-demo-apps/commit/718406a7c591dd43a6328f01872adbcc9d524272

**Comment by jimitndiaye** [comment] 2016-07-08 10:11
@benorama you need to make sure StateUpdates is provided either by using runeffects with a non-empty effects array or by directly including it in your providers.

**Comment by Daskus1** [comment] 2016-07-26 21:50
I have a similar issue... 
I am using Ionic2 Beta10 and Angular RC3
In my case there are no errors but the effect is not triggered. I tried `runEffects` as well as `mergeEffects` but i don't get it to work.
Did you solve it?

**Comment by benorama** [comment] 2016-07-29 12:49
@Daskus1 it looks like this issue is linked to `npm link` that we are using in https://github.com/benorama/ngrx-demo-apps.

When installing the core module locally, it should work.
My team did try to find some workaround by manually doing some manual virtual links. I'm currently in holidays, but I'll post their workaround when I'll be back.

**Comment by Daskus1** [comment] 2016-07-29 18:51
@benorama thank you, that would be nice!

**Comment by Daskus1** [comment] 2016-08-21 18:46
After upgrading Ionic to beta 11 and Angular to rc4 the problem is still there...
@benorama can you please post your workaround?

**Comment by SebastianGiro** [comment] 2016-08-23 20:20
@Dasku1 The problem is back in the new beta11 if you use @ngrx/store@2.0.1

**Comment by SebastianGiro** [comment] 2016-08-23 21:01
@Daskus1 I was able to do it now. 
Make sure you install ionicbeta11 with this command if you use Angular rc4
`npm install --save --save-exact ionic-angular@2.0.0-beta.11 @angular/common@2.0.0-rc.4 @angular/compiler@2.0.0-rc.4 @angular/core@2.0.0-rc.4 @angular/http@2.0.0-rc.4 @angular/platform-browser@2.0.0-rc.4 @angular/platform-browser-dynamic@2.0.0-rc.4 @angular/forms@0.2.0 rxjs@5.0.0-beta.6 zone.js@0.6.12`

Then in your package.json you need to have:

"@ngrx/core": "1.0.1",
"@ngrx/effects": "1.0.1",
"@ngrx/store": "2.0.1",

Delete your node_modules and then do:
`npm install`

Make sure you use your custom module NOT with npm link (copy your custom module dist folder into the node_modules of your project)

Tell me what happens

**Comment by Daskus1** [comment] 2016-08-25 17:48
@SebastianGiro I tried to do exactly what you wrote. There are no more errors, so thats good :)
But the effect is not executed. 
What do you mean by 

> Make sure you use your custom module NOT with npm link (copy your custom module dist folder into the node_modules of your project)

?

**Comment by benorama** [comment] 2016-08-25 18:05
I think that this issue will probably goes away with angular rc5, next ionic beta and ngrx/effects 2.x.
Bootstrapping has been refactored based on NgModule.

**Comment by SebastianGiro** [comment] 2016-08-25 18:34
@Daskus1 Like Ben said, beta12 will have ngrx, and  it will (hopefully) fix all the problems that came out with the angular RC5 release messing with the Ionic2 packages.
So you can just wait for the ionic beta12 release that fixes these issues with ngrx.

> Make sure you use your custom module NOT with npm link (copy your custom module dist folder into the node_modules of your project)

This is if you are using `npm link`, the errors are caused by that.
(you can check if you have a symlink on your `node_modules`)
If you are not using `npm link`, you might have something wrong in your app bootstrap. 

This is my bootstraping code in app.ts:
`ionicBootstrap(AppComponent, [
    provideStore(REDUCER_PROVIDERS),
    { provide: AppStore, useExisting: Store },
    runEffects(EFFECTS_PROVIDERS), // Not works with npm link
    SERVICE_PROVIDERS,
    ACTION_PROVIDERS
  ]);`

We have a script that replace the functionality of `npm link` to work with ionic2@beta-11, let me know and I'll share it with you.

**Comment by Daskus1** [comment] 2016-08-25 18:40
Since I'm working on another project right now I can wait till beta12. Hopefully everything will work fine with it.
Thanks for the help!

**Comment by jimitndiaye** [comment] 2016-08-25 22:38
To everyone struggling with this problem - you can avoid the whole issue by not using runEffects, which is is just a small wrapper around mergeEffects(effectClassInstances).subscribe(store).
Instead of listing runEffects in your providers you can just provide StateUpdates then use dependency injection to get instances of your effect classes to pass to mergeEffects which gives you an Observable you can then subscribe to the store. It boils down to just a couple of lines of code. You gain the added benefit of being able to run effects at any point in your application (including lazy loaded modules) not just at startup.

**Comment by MikeRyan52** [comment] 2016-09-27 00:36
Should be fixed in v2.0.0. Let me know if you have any issues using @ngrx/effects with the latest versions of Ionic by opening up a new issue. Thanks!

**Closed by MikeRyan52** 2016-09-27 00:36 UTC
